name: Generate ASCII atwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6
            
            - name: Install cowsay Program
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay CMD
              run: cowsay -f dragon "Run for cover, I am a DRAGON .... RAWR" >> dragon.txt
              
            - name: Test File exists
              run: grep -i "dragon" dragon.txt
            
            - name: Read File
              run: cat dragon.txt


            - name: List Repo Repo Files
              run: ls -ltra
              