name: Exploring Variables and Secrets

on:
    push

jobs:
    # docker:
    #     runs-on: ubuntu-latest
    #     steps:
    #     - name: Docker Build
    #       run: docker build -t docker.io/dockerUsername/imageName:latest
 
    #     - name: Docker Login
    #       run: docker login --username=dockerUsername --password=s2cUrePaSsw0rd

    #     - name: Docker Publish
    #       run: docker push docker.io/dockerUsername/imageName:latest

    # deploy:
    #     needs: docker
    #     runs-on: ubuntu-latest
    #     steps:
    #       - name: Docker Run
    #         run: docker run -d -p 8080:80 docker.io/dockerUsername/imageName:latest

    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: satyam
            IMAGE_NAME: github-actions-nginx
          run: echo docker build -t  ${{ env.CONTAINER_REGISTRY }}/${{env.DOCKER_USERNAME}}/${{ env.IMAGE_NAME }}:latest

        - name: Docker Login
          env:
            ODCKER_PASSWORD: s2cUrePaSsw0rd
            DOCKER_USERNAME: satyam
          run: echo docker login --username-$DOCKER_USERNAME --password=$ODCKER_PASSWORD
 
        - name: Docker Publish
          env:
            CONTAINER_REGISTRY: docker.io
            DOCKER_USERNAME: satyam
            IMAGE_NAME: github-actions-nginx
          run: echo docker push $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest

    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
          - name: Docker Run
            env:
                CONTAINER_REGISTRY: docker.io
                DOCKER_USERNAME: satyam
                IMAGE_NAME: github-actions-nginx
            run: echo docker run -d -p 8080:80 $CONTAINER_REGISTRY/$DOCKER_USERNAME/$IMAGE_NAME:latest